### ISSUE TITLE
Add Icons to Tree View

### ISSUE THREAD

**Issue by ylor** [k9ordon/yosemite-unity-ui#2]
Thanks for this UI. It's exactly what I was looking for. Would it be possible to add folder and file type icons like some of the other themes, notably [seti-ui](https://atom.io/themes/seti-ui)?

**Comment by dwt** [comment]
Out of interest, is there a specific reason this theme cannot just look up the native icons that the OS uses for these files? That would seem an awful lot more consistent than this?
